//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServer")]
public interface WebServer
{
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServer/updateWorkInstrStatusRequest", ReplyAction="http://tempuri.org/WebServer/updateWorkInstrStatusResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(updateWorkInstrStatusResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(updateWorkInstrStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAlarmOptionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAlarmOption))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(executeResultInfoResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(executeResultInfo))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    updateWorkInstrStatusResponse1 updateWorkInstrStatus(updateWorkInstrStatusRequest request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServer/getAlarmOptionRequest", ReplyAction="http://tempuri.org/WebServer/getAlarmOptionResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(updateWorkInstrStatusResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(updateWorkInstrStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAlarmOptionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAlarmOption))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(executeResultInfoResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(executeResultInfo))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getAlarmOptionResponse1 getAlarmOption(getAlarmOptionRequest request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServer/executeResultInfoRequest", ReplyAction="http://tempuri.org/WebServer/executeResultInfoResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(updateWorkInstrStatusResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(updateWorkInstrStatus))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAlarmOptionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAlarmOption))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(executeResultInfoResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(executeResultInfo))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    executeResultInfoResponse1 executeResultInfo(executeResultInfoRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class updateWorkInstrStatusResponse
{
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class updateWorkInstrStatus
{
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string arg1
    {
        get
        {
            return this.arg1Field;
        }
        set
        {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class getAlarmOptionResponse
{
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class getAlarmOption
{
    
    private string arg0Field;
    
    private string[] arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string[] arg1
    {
        get
        {
            return this.arg1Field;
        }
        set
        {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class executeResultInfoResponse
{
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class executeResultInfo
{
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string arg1
    {
        get
        {
            return this.arg1Field;
        }
        set
        {
            this.arg1Field = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="updateWorkInstrStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class updateWorkInstrStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    public updateWorkInstrStatusRequest()
    {
    }
    
    public updateWorkInstrStatusRequest(string arg0, string arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="updateWorkInstrStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class updateWorkInstrStatusResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return;
    
    public updateWorkInstrStatusResponse1()
    {
    }
    
    public updateWorkInstrStatusResponse1(object @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmOption", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getAlarmOptionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg1;
    
    public getAlarmOptionRequest()
    {
    }
    
    public getAlarmOptionRequest(string arg0, string[] arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getAlarmOptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getAlarmOptionResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return;
    
    public getAlarmOptionResponse1()
    {
    }
    
    public getAlarmOptionResponse1(object @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeResultInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class executeResultInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    public executeResultInfoRequest()
    {
    }
    
    public executeResultInfoRequest(string arg0, string arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeResultInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class executeResultInfoResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return;
    
    public executeResultInfoResponse1()
    {
    }
    
    public executeResultInfoResponse1(object @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface WebServerChannel : WebServer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebServerClient : System.ServiceModel.ClientBase<WebServer>, WebServer
{
    
    public WebServerClient()
    {
    }
    
    public WebServerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebServerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    updateWorkInstrStatusResponse1 WebServer.updateWorkInstrStatus(updateWorkInstrStatusRequest request)
    {
        return base.Channel.updateWorkInstrStatus(request);
    }
    
    public object updateWorkInstrStatus(string arg0, string arg1)
    {
        updateWorkInstrStatusRequest inValue = new updateWorkInstrStatusRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        updateWorkInstrStatusResponse1 retVal = ((WebServer)(this)).updateWorkInstrStatus(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getAlarmOptionResponse1 WebServer.getAlarmOption(getAlarmOptionRequest request)
    {
        return base.Channel.getAlarmOption(request);
    }
    
    public object getAlarmOption(string arg0, string[] arg1)
    {
        getAlarmOptionRequest inValue = new getAlarmOptionRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        getAlarmOptionResponse1 retVal = ((WebServer)(this)).getAlarmOption(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    executeResultInfoResponse1 WebServer.executeResultInfo(executeResultInfoRequest request)
    {
        return base.Channel.executeResultInfo(request);
    }
    
    public object executeResultInfo(string arg0, string arg1)
    {
        executeResultInfoRequest inValue = new executeResultInfoRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        executeResultInfoResponse1 retVal = ((WebServer)(this)).executeResultInfo(inValue);
        return retVal.@return;
    }
}
