//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICabTreeService")]
public interface ICabTreeService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICabTreeService/DoWork", ReplyAction="http://tempuri.org/ICabTreeService/DoWorkResponse")]
    int DoWork(int a);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICabTreeService/DoWork", ReplyAction="http://tempuri.org/ICabTreeService/DoWorkResponse")]
    System.Threading.Tasks.Task<int> DoWorkAsync(int a);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICabTreeServiceChannel : ICabTreeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CabTreeServiceClient : System.ServiceModel.ClientBase<ICabTreeService>, ICabTreeService
{
    
    public CabTreeServiceClient()
    {
    }
    
    public CabTreeServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CabTreeServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CabTreeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CabTreeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int DoWork(int a)
    {
        return base.Channel.DoWork(a);
    }
    
    public System.Threading.Tasks.Task<int> DoWorkAsync(int a)
    {
        return base.Channel.DoWorkAsync(a);
    }
}
